shared:
  environment:
    ECHO4: 4
parameters:
  region: "us-west-1"
  az: 
      value: "zone 1"
      description: "default availability zone"
jobs:
  start:
    image: ubuntu:24.04
    requires:
      - ~commit
    steps:
      - echo 1
      - echo 2
      - echo ${ECHO3}
      - echo ${ECHO4}
    environment:
      ECHO3: 3
  next-job:
    image: ubuntu:24.04
    requires:
      - main
    steps:
     - echo ${ECHO4}